main/urls.py
from django.urls import path, re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    re_path(r'^masuk/$', views.masuk, name='masuk'),
    re_path(r'^daftar/$', views.daftar, name='daftar'),
    re_path(r'^keluar/$', views.keluar, name='keluar'),
]

post_pengumuman/urls.py
from django.urls import path
from . import views

app_name = 'post_pengumuman'

urlpatterns = [
    path('', views.home, name='home'),
    path('<string>/', views.form, name='form'),
]

tk1_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('tips/',include('tips.urls')),
    path('post-pengumuman/', include('post_pengumuman.urls')),
    path('periksa/', include('periksa.urls')),
    
]

post_pengumuman/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Pemerintah(models.Model):
    PROVINSI_CHOICES = (
        ('BAN','Banten'),
        ('JKT','DKI Jakarta'),
        ('JBR','Jawa Barat'),
        ('JTE','Jawa Tengah'),
        ('YOG','DI Yogyakarta'),
        ('JTI','Jawa Timur'),
    )
    provinsi = models.CharField(
        max_length=3,
        choices= PROVINSI_CHOICES,
        default='JKT',
    )

    def __str__(self):
        return self.get_provinsi_display()

class Pengumuman(models.Model):
    PRIORITAS_CHOICES = (
        ('00','Urgent'),
        ('01','Tinggi'),
        ('02','Normal'),
        ('03','Rendah'),
    )
    judul = models.CharField(max_length = 50, blank=False)
    prioritas = models.CharField(
        max_length=2,
        choices= PRIORITAS_CHOICES,
        default='02',
    )
    pemerintah = models.ForeignKey("Pemerintah", default=None, on_delete=models.CASCADE)
    isi_pengumuman = models.TextField(blank=False)

    def __str__(self):
        return '{}-{}-{}'.format(self.judul[:15], self.get_prioritas_display(), str(self.pemerintah))
    
    class Meta:
        ordering = ['prioritas']
        unique_together = ['judul', 'prioritas', 'pemerintah']

post_pengumuman/forms.py
from django.forms import ModelForm, TextInput, Textarea
from .models import Pengumuman

class PengumumanForm(ModelForm):
    class Meta:
        model = Pengumuman
        fields = ['judul', 'prioritas', 'isi_pengumuman']
        widgets = {
            'judul': TextInput(attrs={'placeholder': 'contoh: DKI Jakarta - PSBB Diperpanjang'}),
        }

post_pengumuman/views.py
from django.contrib import messages
from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import render, redirect, reverse
from .models import Pengumuman, Pemerintah
from .forms import PengumumanForm
import json

# Create your views here.
def home(request):
    if not request.user.is_authenticated:
        return redirect(reverse('main:masuk'))
    uname_pemerintah = request.user.username
    return render(request, 'post_pengumuman/post_home.html', {'username': uname_pemerintah})

def form(request, string):
    if not request.user.is_authenticated:
        return redirect(reverse('main:masuk'))
    pemerintah_obj = Pemerintah.objects.get(provinsi = string)
    if request.is_ajax() and request.method == "POST":
        form = PengumumanForm(request.POST)
        if form.is_valid():
            pengumuman_obj = form.save(commit=False)
            pengumuman_obj.pemerintah = pemerintah_obj
            try:
                pengumuman_obj.save()
                data = {
                    'status':'success',
                    'message':'Sukses menambah pengumuman',
                }
                d_str = json.dumps(data) # str of data
                d = json.loads(d_str)    # dict object from string of data
                d.update({
                    'pengumuman': {
                    'judul':pengumuman_obj.judul, 
                    'prioritas':pengumuman_obj.get_prioritas_display(),
                    'isi_pengumuman':pengumuman_obj.isi_pengumuman,
                    }
                })
                # print(json.dumps(d))
                return JsonResponse(d)

            except IntegrityError as e:
                data = {
                    'status':'error',
                    'message':'Gagal: Duplikat pengumuman dengan judul dan prioritas yang sama.',
                }
                return JsonResponse(data)

    else:
        form = PengumumanForm()
    return render(request, 'post_pengumuman/post_form.html', {'provinsi':str(pemerintah_obj), 'form':form, 'kode_prov':string})

post_pengumuman/templates/post_pengumuman/post_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>    
    <script type="text/javascript" src="{% static 'post_pengumuman/script.js' %}"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
    <script src="https://kit.fontawesome.com/fd84aa46ff.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'post_pengumuman/style.css' %}">
    <title>Buat Pengumuman - Risikovid</title>
{% endblock meta %}
{% block content %}
    </div></div>
    <div class="container">
        <div id="messages" class="row justify-content-center mx-2">
        </div>
        <div class="row justify-content-center py-5 mx-2">
            <h2 class="ubuntu text-center">Post Pengumuman</h2>
        </div>
        <div class="row justify-content-center pb-5 px-2">
            <form id="form-pengumuman" method="POST">
                <h3 class="ubuntu pb-2">Pemerintah Provinsi {{provinsi}}</h3>
                {% csrf_token %}
                {{form}}
                <div>
                    <button type="submit">Kirim</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

post_pengumuman/templates/post_pengumuman/post_home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>    
    <script type="text/javascript" src="{% static 'post_pengumuman/script.js' %}"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
    <script src="https://kit.fontawesome.com/fd84aa46ff.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'post_pengumuman/style.css' %}">
    <title>Buat Pengumuman - Risikovid</title>
{% endblock meta %}
{% block content %}
    </div></div>
    <div class="container">
        <div class="row text-center justify-content-center pt-5 pb-1 mx-1">
            <h2 class="ubuntu">Buat Pengumuman</h2>
        </div>
        <div class="row text-center justify-content-center py-1 mx-1">
            <h5 class="ubuntu"><span>Username: </span><span id="username" data-user="{{username|slice:":-5"}}">{{username}}</span></h5>
        </div>
        <div class="row justify-content-center px-4 pb-5">
            <div data-kode-prov="BAN" data-prov="banten" class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'BAN' %}">
                    <img src="{% static 'post_pengumuman/img/Banten.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>
            <div data-kode-prov="JKT" data-prov="jakarta" class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'JKT' %}">
                    <img src="{% static 'post_pengumuman/img/Jakarta.png' %}" class="thumbnail rounded img-fluid" >
                </a>
            </div>
            <div data-kode-prov="JBR" data-prov="jabar" class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'JBR' %}">
                    <img src="{% static 'post_pengumuman/img/West_Java.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>
            <div data-kode-prov="JTE" data-prov="jateng" class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'JTE' %}">
                    <img src="{% static 'post_pengumuman/img/Central_Java.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>
            <div data-kode-prov="YOG" data-prov="yogya" class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'YOG' %}">
                    <img src="{% static 'post_pengumuman/img/Yogyakarta.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>
            <div data-kode-prov="JTI" data-prov="jatim" class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'JTI' %}">
                    <img src="{% static 'post_pengumuman/img/East_Java.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>

        </div>
    </div>
    {% if pengumumans %}
    <div class="container-fluid px-5">
        <div class="header-list py-2">
            <h5 class="ubuntu text-center">Daftar Pengumuman</h5>
            <h6 class="ubuntu text-center">Judul-Urgensi-Provinsi</h6>
        </div>
        <div class="list-pengumuman text-center py-2 mb-5">
            {% for pengumuman in pengumumans %}
                <h6>{{pengumuman}}</h6>
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endblock content %}