main/urls.py
from django.urls import path, re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    re_path(r'^masuk/$', views.masuk, name='masuk'),
    re_path(r'^daftar/$', views.daftar, name='daftar'),
    re_path(r'^keluar/$', views.keluar, name='keluar'),
]

periksa/urls.py
from django.urls import path
from . import views

app_name = 'periksa'

urlpatterns = [
    path('', views.index_periksa, name='index_periksa'),
    path('hasil/', views.hasil_periksa, name='hasil_periksa'),
    path('show/', views.show_pengunjung_periksa, name='show_pengunjung_periksa'),
    path('data/', views.data_pengunjung_periksa, name='data_pengunjung_periksa')
]

tk1_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('tips/',include('tips.urls')),
    path('post-pengumuman/', include('post_pengumuman.urls')),
    path('periksa/', include('periksa.urls')),
    
]

periksa/models.py
from django.db import models

# Create your models here.
class PengunjungPeriksa(models.Model):
    nama = models.TextField(max_length=75)
    daerah = models.TextField()

    def __str__(self):
        return self.nama

periksa/forms.py
from django import forms
from .models import PengunjungPeriksa

class PengunjungPeriksaForm(forms.Form):
    PILIHAN_GEJALA = (
        ("1", "Demam diatas 39 derajat Celcius"),
        ("2", "Batuk-batuk"),
        ("3", "Kesulitan bernapas atau napas pendek"),
        ("4", "Selalu kelelahan"),
        ("5", "Nyeri-nyeri pada otot atau tubuh"),
        ("6", "Sakit kepala"),
        ("7", "Kehilangan kemampuan mencium dan mengecap rasa"),
        ("8", "Sakit tenggorokan"),
        ("9", "Hidung tersumbat atau banyak cairan di hidung"),
        ("10", "Mual atau muntah"),
        ("11", "Diare"),
        ("12", "Pernah bertemu orang dengan gejala COVID-19 dalam selang dua minggu"),
        ("13", "Tidak ada gejala yang saya alami")
    )

    nama = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class" : "form-control prompt",
                "placeholder" : "Masukkan Nama"
            }
        ), 
        label=""
    )

    gejala = forms.MultipleChoiceField(
        choices=PILIHAN_GEJALA,
        widget=forms.CheckboxSelectMultiple(
            attrs={"class" : "prompt"}
        ), label=""
    )

    PILIHAN_DAERAH = [
        ("Banten", "Banten"),
        ("DKI Jakarta", "DKI Jakarta"),
        ("Jawa Barat", "Jawa Barat"),
        ("Jawa Tengah", "Jawa Tengah"),
        ("DI Yogyakarta", "DI Yogyakarta"),
        ("Jawa Timur", "Jawa Timur"),
    ]

    daerah = forms.ChoiceField(
        choices=PILIHAN_DAERAH,
        widget=forms.Select(
            attrs={"class" : "prompt custom-select"}
        ), label=""
    )

periksa/views.py
from django.shortcuts import render, redirect
from .models import PengunjungPeriksa
from .forms import PengunjungPeriksaForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import PengunjungPeriksa
from django.http import JsonResponse

# Create your views here.
def index_periksa(request):
    context = {
        "pengunjung_periksa_form" : PengunjungPeriksaForm
    }
    return render(request, "periksa/index.html", context)

def hasil_periksa(request):
    context = {}
    if request.method == "POST":
        pengunjung_periksa_form = PengunjungPeriksaForm(request.POST)
        if pengunjung_periksa_form.is_valid():
            pengunjung = pengunjung_periksa_form.cleaned_data.get("nama")
            daerah = pengunjung_periksa_form.cleaned_data.get("daerah")
            # Buat perhitungan persentase kena COVID-19
            list_hasil = pengunjung_periksa_form.cleaned_data.get("gejala")
            persentase = round(len(list_hasil)/12 * 100, 3)
            if list_hasil[0] == "13": # "13" = "Tidak ada gejala yang muncul"
                persentase = 0
            elif list_hasil.count("13") > 0 and len(list_hasil) > 1:
                messages.add_message(request, messages.WARNING, "Pilihan saling berkontradiksi. Silakan ulangi pengisian form.")
                return redirect("periksa:index_periksa")
            if persentase <= 35:
                pesan = "Peluang Anda terkena COVID-19 cukup kecil.\
                    Selalu jaga kesehatan dan laksanakan protokol kesehatan\
                    yang berlaku di " + daerah + "."
                context["pesan"] = pesan
            elif persentase <= 70:
                pesan = "Peluang Anda terkena COVID-19 cukup besar.\
                    Direkomendasikan untuk segera melakukan rapid test\
                    di daerah " + daerah + " untuk mengetahui lebih lanjut."
                context["pesan"] = pesan
            else:
                pesan = "Peluang Anda terkena COVID-19 sangat besar.\
                    Segera melapor ke rumah sakit penanganan COVID-19 di daerah " + daerah + "."
                context["pesan"] = pesan

            pengunjung_object = PengunjungPeriksa(nama=pengunjung, daerah=daerah)
            pengunjung_object.save()
            context["persentase_str"] = str(persentase)
            context["pengunjung"] = pengunjung
        else:
            messages.add_message(request, messages.WARNING, "Panjang nama tidak boleh lebih dari 75 karakter atau tidak ada gejala yang dipilih. Silakan ulangi pengisian form.")
            messages.add_message(request, messages.WARNING, "Jika memang tidak punya gejala, silakan pilih opsi 'Tidak ada gejala yang saya alami'.")
            return redirect("periksa:index_periksa")
    return render(request, "periksa/hasil_periksa.html", context)

@login_required(login_url = "/masuk")
def show_pengunjung_periksa(request):
    return render(request, "periksa/show_pengunjung_periksa.html")

def data_pengunjung_periksa(request):
    data = list(PengunjungPeriksa.objects.values())
    return JsonResponse(data, safe=False)

periksa/templates/periksa/hasil_periksa.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hasil Periksa</title>
{% endblock meta %}

{% block content %}
<div class="container py-5 justify-content-center align-items-center">
    <div class="row m-5 p-3 bg-light rounded-lg">
        <div class="col text-center">
            <h2>Hasil Periksa</h2>
            <br>
            <p>Peluang {{ pengunjung }} terkena COVID-19 adalah {{ persentase_str }}%</p>
            <p>{{ pesan }}</p>
            {% if not user.is_authenticated %}
            <p><a href="{% url 'periksa:show_pengunjung_periksa' %}" class="text-dark">Klik disini untuk melihat pengunjung lainnya.</a> Catatan: Login dahulu, kemudain pergi lagi ke bagian periksa</p>
            {% else %}
            <p><a href="{% url 'periksa:show_pengunjung_periksa' %}" class="text-dark">Klik disini untuk melihat pengunjung lainnya.</a></p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

periksa/templates/periksa/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Periksa</title>
{% endblock meta %}

{% block content %}
<div class="py-5">
    {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible show fade" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}
    <div class="container">
        <div class="row pt-1 pb-5">
            <div class="col">
                <h2 class="text-center ubuntu">Periksa Gejala Anda</h2>
            </div>
        </div>
        <div class="row mx-1 p-4 bg-light rounded-lg">
            <div class="col">
                <form action="{% url 'periksa:hasil_periksa' %}" method="POST" id="form-periksa">
                    {% csrf_token %}
                    <div class="form-group row justify-content-center">
                        <label class="col-sm-2 col-form-label prompt">Nama</label>
                        <div class="col-sm-4">
                            {{ pengunjung_periksa_form.nama }}
                        </div>
                    </div>
                    <div class="form-group row justify-content-center">
                        <label class="col-sm-2 col-form-label prompt">Daerah</label>
                        <div class="col-sm-4">
                            {{ pengunjung_periksa_form.daerah }}
                        </div>
                    </div>
                    <div class="row text-center justify-content-center pt-3">
                        <div class="col-md-8">
                            Silakan klik pada gejala yang sesuai dengan keadaan Anda.
                            Tekan panah ke kiri atau ke kanan untuk melanjutkan.
                            Jika sudah selesai, klik "Hitung persentase".
                        </div>
                    </div>
                    
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="false">
                        <div class="carousel-inner text-center" style="height: 10rem;" id="tes-gejala">
                            {% for choice in pengunjung_periksa_form.gejala %}
                                {% if forloop.first %}
                                <div class="carousel-item active p-5 prompt">
                                    {{ choice }}
                                </div>
                                {% else %}
                                <div class="carousel-item p-5 prompt">
                                    {{ choice }}
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <div class="row justify-content-center mb-5">
                        <input class="is-navy text-light rounded-pill spinnaker p-3" type="submit" id="btn-submit"value="Hitung Persentase">
                    </div>
                </form>
                <div class="col text-center text-light height-qotd border rounded-lg" id="qotd">
                    Arahkan mouse ke sini
                </div>
                {% if user.is_authenticated %}
                <p class="text-center mt-4"><a href="{% url 'periksa:show_pengunjung_periksa' %}" class="text-dark">Klik disini untuk melihat pengunjung lainnya.</a></p>
                {% endif %}
            </div>
        </div>
    </div>

</div>

<script src="{% static 'js/script_periksa.js' %}"></script>
{% endblock content %}

periksa/templates/periksa/show_pengunjung_periksa.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Pengunjung Periksa Lainnya</title>
{% endblock meta %}

{% block content %}
<section class="d-flex text-center justify-content-center align-items-center text-dark flex-column home-height">
    <div class="container bg-light" id="container-pengunjung-periksa">
        <h3 class="text-center">Daftar Pengunjung Fitur Periksa</h3>
        <ul id="list-pengunjung-periksa">

        </ul>
    </div>
    <button class="btn btn-primary" id="btn-data">Munculkan Pengunjung Periksa</button>
</section>

<script src="{% static 'js/script_periksa.js' %}"></script>
{% endblock content %}