main/urls.py
from django.urls import path, re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    re_path(r'^masuk/$', views.masuk, name='masuk'),
    re_path(r'^daftar/$', views.daftar, name='daftar'),
    re_path(r'^keluar/$', views.keluar, name='keluar'),
]

tk1_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('tips/',include('tips.urls')),
    path('post-pengumuman/', include('post_pengumuman.urls')),
    path('periksa/', include('periksa.urls')),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <!--
    Navbar source: https://www.codeply.com/go/kTGlK9Axdk 
  -->

  <div class="header is-navy py-2" id="navbar-base">
    <div class="container">
      <nav class="navbar navbar-expand-md navbar-dark" >
        <a href="{% url 'main:home' %}" class="navbar-brand">risicovid</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar7">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-stretch" id="navbar7">
            <ul class="navbar-nav ml-auto">
                {% if is_pemprov %}
                  <li class="nav-item">
                    <a class="nav-link" href="/post-pengumuman/">post pengumuman</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="/periksa/">periksa</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">rumah sakit</a>
                </li>
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="/tips/">tips</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:keluar' %}">keluar</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:daftar' %}">daftar</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:masuk' %}">masuk</a>
                  </li>
                {% endif %}
            </ul>
        </div>
      </nav>
    </div>
  </div>

  
  {% block content %}
  {% endblock content %}
  <footer class="text-center">
    <p>© 2020 risicovid</p>
  </footer>
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
</body>

</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="d-flex justify-content-center align-items-center text-dark flex-column home-height">
  <form method="POST" action="{% url 'main:masuk' %}" class="login-form bg-light rounded-lg d-flex flex-column justify-content-center p-4">
      <h3 class="text-center mb-3">Login</h3>
      {% csrf_token %}
      {{ form }}
      <button type="submit" id="btn_login" class="btn btn-primary">Login</button>
      <div class="card-footer">
          <div class="d-flex justify-content-center links">
            Don't have an account? =><a class="text-dark"href="{% url 'main:daftar' %}"> Create a new one here</a>
          </div>
      </div>
  </form>
</section>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="d-flex justify-content-center align-items-center text-dark flex-column home-height">
  <form method="POST" action="{% url 'main:daftar' %}" class="login-form bg-light rounded-lg d-flex flex-column justify-content-center p-4">
      <h3 class="text-center mb-3">Register</h3>
      {% csrf_token %}
      {{ form }}
      <button type="submit" id="btn_login" class="btn btn-primary">Register</button>
      <div class="card-footer">
          <div class="d-flex justify-content-center links">
            Already have an account? =><a class="text-dark"href="{% url 'main:masuk' %}"> Login here</a>
          </div>
      </div>
  </form>
</section>
{% endblock %}