main/urls.py
from django.urls import path, re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    re_path(r'^masuk/$', views.masuk, name='masuk'),
    re_path(r'^daftar/$', views.daftar, name='daftar'),
    re_path(r'^keluar/$', views.keluar, name='keluar'),
]

tips/urls.py
from django.urls import path

from . import views
# from main.views import home

app_name = 'tips'

urlpatterns = [
    path('', views.tips, name = 'tips'),
    path('hapus-tips/', views.hapusTips, name = 'hapusTips'),
    path('get_pembuat/', views.get_pembuat, name = "pembuat")
]

tk1_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('tips/',include('tips.urls')),
    path('post-pengumuman/', include('post_pengumuman.urls')),
    path('periksa/', include('periksa.urls')),
    
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class SignUpForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Insert username"
    }))

    password1 = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Insert Password",
        "type" : "password"
    }))

    password2 = forms.CharField(label="Confirm Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Type the same Password",
        "type" : "password"
    }))

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Insert Username"
    }))

    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Insert Password",
        "type" : "password"
    }))

    class Meta:
        fields = "__all__"

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView
from post_pengumuman.models import Pengumuman
from tips.models import tips
from django.contrib import messages
from .forms import SignUpForm, LoginForm

class HomeView(ListView):
    template_name = 'main/home.html'
    context_object_name = 'pengumuman_list'

    def get_queryset(self):
        return Pengumuman.objects.order_by('prioritas')

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context.update({
            'tips_list':tips.objects.all(),
            'is_pemprov':self.request.user.groups.filter(name="pemprov").exists(),
        })
        return context

def masuk(request):
    if request.user.is_authenticated:
        return redirect(reverse("main:home"))
    if request.method == 'POST':
        form = LoginForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect(reverse('main:home'))
    else:
        form = LoginForm
    return render(request, 'login.html', {'form': form})

def daftar(request):
    if request.user.is_authenticated:
        return redirect(reverse("main:home"))
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            new_user_account = authenticate(
                username = form.cleaned_data["username"],
                password = form.cleaned_data["password1"]
            )
            # Langsung loginkan user yang sudah authenticated.
            login(request, new_user_account)
            return redirect(reverse('main:home'))
    else:
        form = SignUpForm
    return render(request, 'signup.html', {'form': form})

def keluar(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect(reverse('main:home'))

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>risicovid</title>
{% endblock meta %}

{% block content %}
  <div class="container my-5 py-5">
    <div class="row align-items-center mx-1 py-3">
      <div class="col-sm-6 order-sm-12 my-2 px-1 text-center">
        <img class="img-fluid" src="/static/img/landing.svg" style="max-width: 90%;"></img>
      </div>
      <div class="col-sm-6 order-sm-1 my-3 pt-3">
        <h1 class="ubuntu">
          Cek kondisimu jika terdapat gejala COVID-19
        </h1>
        <div class="row">
          <a class="btn is-navy btn-dark btn-lg ml-3 spinnaker" href="/periksa/" role="button">Periksa</a>
          <a class="btn is-navy btn-dark btn-lg ml-3 spinnaker" href="#" role="button">Rumah Sakit</a>
        </div>
      </div>
    </div>
  </div>
  <div class="container my-5">
    <h2 class="ubuntu">Pengumuman</h2>
    <div id="carouselExampleControls" class="carousel slide p-3" data-ride="carousel">
      <ol class="carousel-indicators">
        {% for i in pengumuman_list %}
          <li data-target="#carouselExampleIndicators" data-slide-to={{forloop.counter0}} class="active"></li>
        {% endfor %}
      </ol>
      <div class="carousel-inner bg-light rounded">
          {% if pengumuman_list %}
            {% for pengumuman in pengumuman_list %}
              {% if forloop.first %}
              <div class="carousel-item active p-5 prompt">
                <p class="border border-right-0 border-left-0 border-info mx-2 my-2 text-center">{{pengumuman.judul|title}}</p>
                <p class="mx-2 mb-0">
                  <span class="font-weight-bold">Provinsi : </span>
                  <span class="d-inline-block">{{pengumuman.pemerintah}}
                </p>
                <p class="mx-2 mb-0">
                    <span class="font-weight-bold">Urgensi  : </span>
                  {% if pengumuman.prioritas == '00' %} 
                    <span class="px-2 d-inline-block bg-danger">{{pengumuman.get_prioritas_display}}
                  {% elif pengumuman.prioritas == '01' %} 
                    <span class="px-2 d-inline-block bg-warning">{{pengumuman.get_prioritas_display}}
                  {% else %} 
                    <span class="d-inline-block">{{pengumuman.get_prioritas_display}}
                  {% endif %}
                </p>
                <p class="mx-2 my-2 text-center font-italic">"{{pengumuman.isi_pengumuman}}"</p>
              </div>
              {% else %}
              <div class="carousel-item p-5 prompt">
                <p class="border border-right-0 border-left-0 border-info mx-2 my-2 text-center">{{pengumuman.judul|title}}</p>
                <p class="mx-2 mb-0">
                  <span class="font-weight-bold">Provinsi : </span>
                  <span class="d-inline-block">{{pengumuman.pemerintah}}
                </p>
                <p class="mx-2 mb-0">
                    <span class="font-weight-bold">Urgensi  : </span>
                  {% if pengumuman.prioritas == '00' %} 
                    <span class="px-2 d-inline-block bg-danger">{{pengumuman.get_prioritas_display}}
                  {% elif pengumuman.prioritas == '01' %} 
                    <span class="px-2 d-inline-block bg-warning">{{pengumuman.get_prioritas_display}}
                  {% else %}
                    <span class="d-inline-block">{{pengumuman.get_prioritas_display}}
                  {% endif %}
                </p>
                <p class="mx-2 my-2 text-center font-italic">"{{pengumuman.isi_pengumuman}}"</p>
              </div>
              {% endif %}
            {% endfor %}
          {% else %}
            <div class="carousel-item text-center p-5 prompt">
              <p>Belum ada pengumuman</p>
            </div>
          {% endif %}
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="container my-5" id="tips">
    <h2 class="ubuntu text-center">Selalu jaga kesehatan dengan mengikuti tips di bawah ini</h2>
    <ul class="list-group p-3">
      {% for i in tips_list %}
        <li class="list-group-item mb-1 rounded border-0">
          <p class="mb-0 prompt">
            <span class="border rounded border-info px-2 mx-2">{{forloop.counter}}</span>
            {{i.pesan|capfirst}}
            {% if user.is_authenticated %}
            <button value="{{ i.id }}" type="button" class="btn btn-danger delete" style="float: right;">X</button>
            <button value="{{ i.id }}" type="button" class="btn btn-dark question" style="float: right;">?</button>
            {% endif %}
          </p>
        </li>
      {% endfor %}
    </ul>  
  </div>

<script type = "text/javascript">
$(document).ready(function(){
    $(".delete").click(function() {
        var id = $(this).val()
        console.log(id)
        if (confirm("Ingin menghapus tips?")) {
          $.ajax({
            url: "{% url 'tips:hapusTips' %}",
            type: "GET",
            data: {
              'id' : id,
              },
            success: function(response){
              location.reload()
            }
        })
        }
    })
    $(".question").click(function(){
      var id = $(this).val()
      console.log(id)
      $.ajax({
        url:"{% url 'tips:pembuat' %}",
        type: "GET",
        data:{'id':id},
        success: function(response) {
          alert("The creator is " + response["0"].nama)
          console.log(response.items)
        }
      })
    })
});
</script>
{% endblock content %}